version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Choose either one of the orbs below
    # welcome: circleci/welcome-orb@0.4.1
    # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
    configure_infrastructure: 
        docker:
          - image: python:3.7-alpine3.11
        steps:
          - checkout
          - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints: ["1a:34:ad:10:81:64:fd:40:4e:41:5b:b4:df:ec:60:2e"] 
          - run:
              name: Install Ansible
              command: |
                apk add --update ansible
          - run:
              name: Run Playbook and Configure server
              command: |
                ansible-playbook -i [inventory-file] [playbook-file]
    create_infrastructure:
        docker:
          - image: amazon/aws-cli
        steps:
          - checkout
          - run:
              name: Create Cloudformation Stack
              command: |
                aws cloudformation deploy \
                  --template-file template.yml \
                  --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                  --region us-east-1
# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        - create_infrastructure
